server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lc
    password: 5939523
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null




api:
  info:
    title: Learning Center
    description: This online learning center created for managing all information about everything
    version: 1.0
    termOfService: http://murotboyev-bekzodbek.us-east-1.elasticbeanstalk.com
    contact-name: Bekzodbek Murotboyev
    contact-email: http://murotboyev-bekzodbek.us-east-1.elasticbeanstalk.com
    contact-url: http://murotboyev-bekzodbek.us-east-1.elasticbeanstalk.com
    license-name: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs
